wallpaper {
    monitor = DP-3
    path = /home/lieke/Documenten/Wallpaper/bg.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = /home/lieke/Documenten/Wallpaper/bg.jpg
    fit_mode = cover
}

splash = false
